module.exports = [
  // Add bowler names here - they will be assigned role: "bowler"
  // All other players will default to role: "batter"
  "Kagiso Rabada",
    "Trent Boult",
    "Mohammed Shami",
    "Yuzvendra Chahal",
    "Arshdeep Singh",
    "Kuldeep Yadav",
    "Tushar Deshpande",
    "Mayank Yadav",
    "Rashid Khan",
    "Ravi Bishnoi",
    "Sunil Narine",
    "T Natarajan",
    "Lungi Ngidi",
    "Sandeep Sharma",
    "Harshal Patel",
    "Prasidh Krishna",
    "Varun Chakravarthy",
    "Deepak Chahar",
    "T Natarajan",
    "Jofra Archer",
    "Vaibhav Arora",
    "Hazlewood",
    "Matt Henry",
    "Mohammed Siraj",
    "Bhuvneshwar Kumar",
    "Suyash Sharma",
    "Avesh Khan",
    "Khaleel Ahmed",
    "Noor Ahmed",
    "Starc",
    "Sai kishore",
    "Pathirana",
    "Digvesh",
  "Jasprit Bumrah"
];
